# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{test-mysqld}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["miyucy"]
  s.date = %q{2011-05-19}
  s.description = %q{port of Test::mysqld (mysqld runner for tests)}
  s.email = %q{miyucy@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/test/mysqld.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/test-mysqld_spec.rb",
    "test-mysqld.gemspec"
  ]
  s.homepage = %q{http://github.com/miyucy/test-mysqld}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{port of Test::mysqld}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/test-mysqld_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

